apiVersion: v1
kind: Pod
metadata:
  name: dns-lab
  namespace: muma-bank-labs
  labels:
    lab: dns
spec:
  restartPolicy: Never
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: resolver
      image: muma-bank:dev
      imagePullPolicy: Never
      command: ["python", "-c"]
      args:
        - "import socket; socket.getaddrinfo('missing-service.muma-bank.svc.cluster.local', 80)"
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
