apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-pull-lab
  namespace: muma-bank-labs
spec:
  replicas: 1
  selector:
    matchLabels:
      lab: image-pull
  template:
    metadata:
      labels:
        lab: image-pull
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: application
          image: muma-bank:missing
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
