apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-lab
  namespace: muma-bank-labs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: unavailable-storage-class
  resources:
    requests:
      storage: 64Mi
