apiVersion: v1
kind: Namespace
metadata:
  name: muma-bank-labs
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    app.kubernetes.io/part-of: muma-bank-platform
